backend:
  name: github
  repo: dillionmegida/dillionmegida.com
media_folder: "static/img/uploads"
public_folder: "img/uploads"
collections:
  - name: "blogs"
    label: "Blogs"
    description: "Blog posts"
    folder: "src/pages/p"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date }
      - { name: readTime, label: Read Time }
      - { name: pageDescription, label: Excerpt / Page Description }
      - { name: pageKeywords, label: SEO Keywords }
      - { name: tags, label: Blog Tags, widget: list, required: false }
      - { name: cover, label: Blog Cover Link, required: false }
      - { name: body, label: Body, widget: markdown }
publish_mode: editorial_workflow